### ISSUE TITLE
characteristic value expected valid finite number and received "undefined" (undefined).

### ISSUE THREAD

**Issue by Zahnweh** [ingowalther/homebridge-advanced-http-temperature-humidity#5]
Thanks a lot for providing this plug-in! It's all working fine, but my homebridge produces a warning:

[18/05/2021, 11:36:42] [homebridge-advanced-http-temperature-humidity] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

As it's all working this is not to be considered a showstopper ;) But maybe this helps for a future update. Thank you!

**Comment by ingowalther** [comment]
Could it possibly be that your endpoint does not return a value for the humidity?

**Comment by Zahnweh** [comment]
Here's what it returns:

{
"temperature": 21.60,
 "humidity": 34.00
}

**Comment by ingowalther** [comment]
Unfortunately, I don't currently have homebridge running. 
Therefore I can not reproduce the error :(

But I think I have fixed the error with https://github.com/ingowalther/homebridge-advanced-http-temperature-humidity/commit/85d2055cef6e4eeca0f8d1d91e08852de86dc352. Please try version 1.0.3

**Comment by Zahnweh** [comment]
The error remains the same with 1.0.3. Thanks for trying anyway. Let me know if can help out providing additional information.

**Comment by Zahnweh** [comment]
Hello again, after updating nodejs and rebooting homebridge the error doesn't show up anymore. I don't know whether it was the update or the reboot to have solved the problem, but anyway. Thanks a lot!
